In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/2022-ml-midterm-p2/submit.csv
/kaggle/input/2022-ml-midterm-p2/train.csv
/kaggle/input/2022-ml-midterm-p2/test.csv


In [2]:
import random
import os
seed = 42
random.seed(seed)
np.random.seed(seed)
os.environ["PYTHONHASHSEED"] = str(seed)

In [3]:
train=pd.read_csv('/kaggle/input/2022-ml-midterm-p2/train.csv')
test=pd.read_csv('/kaggle/input/2022-ml-midterm-p2/test.csv')
submit=pd.read_csv('/kaggle/input/2022-ml-midterm-p2/submit.csv')

In [4]:
train.head()

index  0  1  2   3   4   5  6  7  8  ...  55  56  57  58  59  60  61  62  \
0      0  0  0  5  13   9   1  0  0  0  ...   0   0   0   6  13  10   0   0   
1      1  0  0  0  12  13   5  0  0  0  ...   0   0   0   0  11  16  10   0   
2      2  0  0  0   4  15  12  0  0  0  ...   0   0   0   0   3  11  16   9   
3      3  0  0  7  15  13   1  0  0  0  ...   0   0   0   7  13  13   9   0   
4      4  0  0  0   1  11   0  0  0  0  ...   0   0   0   0   2  16   4   0   

   63  label  
0   0      0  
1   0      1  
2   0      2  
3   0      3  
4   0      4  

[5 rows x 66 columns]

In [5]:
test.head()

index    0    1     2     3     4     5     6    7    8  ...    54   55  \
0     23  0.0  1.0   8.0  12.0  15.0  14.0   4.0  0.0  0.0  ...   0.0  0.0   
1     29  0.0  0.0   9.0  13.0   7.0   0.0   0.0  0.0  0.0  ...  16.0  2.0   
2     30  0.0  0.0  10.0  14.0  11.0   3.0   0.0  0.0  0.0  ...   0.0  0.0   
3     32  0.0  2.0  13.0  16.0  16.0  16.0  11.0  0.0  0.0  ...   0.0  0.0   
4     44  0.0  0.0   9.0  16.0  16.0  16.0   5.0  0.0  0.0  ...   0.0  0.0   

    56   57    58    59    60    61    62   63  
0  0.0  0.0  14.0  15.0  11.0   2.0   0.0  0.0  
1  0.0  0.0   7.0  12.0  12.0  12.0  11.0  0.0  
2  0.0  0.0  11.0  16.0  12.0   3.0   0.0  0.0  
3  0.0  2.0  16.0  15.0   8.0   0.0   0.0  0.0  
4  0.0  0.0  13.0  10.0   0.0   0.0   0.0  0.0  

[5 rows x 65 columns]

In [6]:
submit.head()

index  label
0     23    NaN
1     29    NaN
2     30    NaN
3     32    NaN
4     44    NaN

In [7]:
print(train.shape, test.shape, submit.shape)

(1437, 66) (360, 65) (360, 2)


In [8]:
for c in train.columns:
    print(train[c].unique())

[   0    1    2 ... 1794 1795 1796]
[0]
[0 2 5 6 3 1 4 7 8]
[ 5  0  7 12  9 11  1 10  6  3  8  2 13 15  4 14 16]
[13 12  4 15  1 10  8 14  9  0  7  2 16 11  5  6  3]
[ 9 13 15 11  0  8 14  1 16  4  5 12 10  2  6  7  3]
[ 1  5 12  0 16 11 13  9 10  7  2  3 14  8  6  4 15]
[ 0 15  1  3  2  4  6  8  5 10  7 11 16  9 14 12 13]
[ 0  1 10 11  2  7  6 13  5 12  4  9 14  8  3 15]
[0 1 2]
[ 0  8  2  4 11  3  1  5  7  6  9 12 10 13 14 16 15]
[13  0  3 14  5  7 12 16 11 15  1  9  8 10  6  4  2]
[15 11 16  6  7 14  5  8 12 10  4 13  2  9  3  1  0]
[10 16 15  8  4 14  7  9 13 12 11  6  3  5  0  1  2]
[15  9 14  4  0 11 12 13 16  1  7  2  6  5  3 10  8]
[ 5  0 12  6  2  8  1 11  3  7  4  9 10 15 16 14 13]
[ 0  3  5  8  9  1  6  7 12 10  2  4 11]
[0 1 2]
[ 3  0  2  8  5  4  1  6  9 14  7 10 12 11 16 15 13]
[15  3  8  1 13  0  9 16 10 14  4  5  7  6 11  2 12]
[ 2 15 13 16  0 10 12 14  1  6 11  9  8  4  7  3  5]
[ 0 16  8 13  6 15  3 10 12 14  1  7  2 11  5  9  4]
[11  6 16  0  2 10 13 15 14  9 12  3  

In [9]:
for c in test.columns:
    print(test[c].unique())

[  23   29   30   32   44   49   51   59   65   67   69   70   71   73
   76   78   99  109  111  115  123  124  135  141  162  168  170  173
  184  185  188  196  203  210  212  220  233  237  239  240  244  247
  250  251  254  259  261  270  271  275  289  297  298  300  303  305
  307  316  322  324  331  332  339  342  344  350  351  352  354  365
  366  367  371  374  381  382  383  394  398  408  411  413  415  416
  422  427  429  432  438  439  450  464  471  478  479  480  481  482
  483  486  495  497  514  518  526  527  530  532  534  535  538  543
  544  554  555  557  567  570  576  582  584  585  588  589  590  591
  599  602  609  610  611  613  617  618  619  631  637  643  650  651
  660  669  674  677  679  692  694  701  707  712  730  743  752  754
  759  767  774  778  787  792  798  799  809  813  818  824  832  839
  841  844  845  849  857  861  865  867  887  888  900  903  909  915
  930  931  937  938  940  952  962  964  965  966  968  979  984  993
  999 

In [10]:
X_train=train.drop(['index','label'],axis=1)
y_train=train['label']
X_test=test.drop(['index'],axis=1)

In [11]:
print(X_train.shape, y_train.shape ,X_test.shape)

(1437, 64) (1437,) (360, 64)


In [12]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier()
neigh.fit(X_train,y_train)

KNeighborsClassifier()

In [13]:
y_test_pred_knnclf=neigh.predict(X_test)

In [14]:
submit['label']=y_test_pred_knnclf
submit.to_csv('submit.csv',index=False) 